### ISSUE TITLE
Is it possible tu send also to the user ? 

### ISSUE THREAD

**Issue by gstechnik** [MissVeronica/um-additional-email-recipients#1]
Hi , im looking for the possibility to send an email directed to the adimn (Account verification request) also to the user with instructions to get verified.

i tried with {email} but this does not seem to work. 

Is this somehow possible with this plugin? 

Thanks

**Comment by MissVeronica** [comment]
you can read this guide about registration and approvals/verifications
https://docs.ultimatemember.com/article/1652-how-to-enable-email-notification-on-activation-or-admin-review-upon-users-registration
